# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95f279ede59a90b33d0b219fee2635bb66a627a89e36026537034e868e2e4fa78ebb4340c6c2b6f01cfb6d246051ed7c8c92e407b4d8c64209f20ca38536f91

test:
  secret_key_base: 19d5bb2a6de7f1c94fe8d3fd96ececa82b576d0721faf4ae064410d11367dcf854a4c118777f76faf87ae59ad5294899f73602f5e49823d8b0383eb5822c9ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
